### ISSUE TITLE
Hot Reload not working after an error in NextJS 14 with App Router

### ISSUE THREAD

**Issue by theaafofficial** [aidenybai/million#878] opened 2024-01-09 16:50 UTC
### What version of `million` are you using?

2.6.4

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

Whenever an error occurs, hot-reload stops working and gets stuck there.
This is an error 
 ⨯ unhandledRejection: SyntaxError: D:\codebase\pod-webapp\src\app\home\orders\detail\page.jsx: JSX attributes must only be assigned a non-empty expression. (149:65)

  147 |                 <h1 className="text-md font-bold">Order Items</h1>
  148 |               </div>
> 149 |               <Accordion title="Order Items" defaultExpandedKeys={}>
      |                                                                  ^
  150 |                 {order?.order_items?.map((item) => {
  151 |                   return (
  152 |                     <AccordionItem
    at constructor (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:356:19)
    at JSXParserMixin.raise (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:3223:19)
    at JSXParserMixin.jsxParseAttributeValue (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:6762:16)
    at JSXParserMixin.jsxParseAttribute (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:6813:38)
    at JSXParserMixin.jsxParseOpeningElementAfterName (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:6827:28)
    at JSXParserMixin.jsxParseOpeningElementAt (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:6822:17)
    at JSXParserMixin.jsxParseElementAt (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:6846:33)
    at JSXParserMixin.jsxParseElementAt (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:6858:32)
    at JSXParserMixin.jsxParseElementAt (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:6858:32)
    at JSXParserMixin.jsxParseElementAt (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:6858:32)
    at JSXParserMixin.jsxParseElementAt (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:6858:32)
    at JSXParserMixin.jsxParseElementAt (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:6858:32)
    at JSXParserMixin.jsxParseElement (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:6915:17)
    at JSXParserMixin.parseExprAtom (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:6927:19)
    at JSXParserMixin.parseExprSubscripts (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:10857:23)
    at JSXParserMixin.parseUpdate (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:10840:21)
    at JSXParserMixin.parseMaybeUnary (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:10816:23)
    at JSXParserMixin.parseMaybeUnaryOrPrivate (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:10654:61)
    at JSXParserMixin.parseExprOps (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:10659:23)
    at JSXParserMixin.parseMaybeConditional (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:10636:23)
    at JSXParserMixin.parseMaybeAssign (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:10597:21)
    at D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:10567:39
    at JSXParserMixin.allowInAnd (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:12284:12)
    at JSXParserMixin.parseMaybeAssignAllowIn (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:10567:17)
    at JSXParserMixin.parseParenAndDistinguishExpression (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:11499:28)
    at JSXParserMixin.parseExprAtom (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:11137:23)
    at JSXParserMixin.parseExprAtom (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:6932:20)
    at JSXParserMixin.parseExprSubscripts (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:10857:23)
    at JSXParserMixin.parseUpdate (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:10840:21)
    at JSXParserMixin.parseMaybeUnary (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:10816:23)
    at JSXParserMixin.parseMaybeUnaryOrPrivate (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:10654:61)
    at JSXParserMixin.parseExprOps (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:10659:23)
    at JSXParserMixin.parseMaybeConditional (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:10636:23)
    at JSXParserMixin.parseMaybeAssign (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:10597:21)
    at JSXParserMixin.parseExpressionBase (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:10551:23)
    at D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:10547:39
    at JSXParserMixin.allowInAnd (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:12279:16)
    at JSXParserMixin.parseExpression (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:10547:17)
    at JSXParserMixin.parseReturnStatement (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:13003:28)
    at JSXParserMixin.parseStatementContent (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:12621:21)
    at JSXParserMixin.parseStatementLike (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:12588:17)
    at JSXParserMixin.parseStatementListItem (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:12568:17)
    at JSXParserMixin.parseBlockOrModuleBlockBody (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:13189:61)
    at JSXParserMixin.parseBlockBody (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:13182:10)
    at JSXParserMixin.parseBlock (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:13170:10)
    at JSXParserMixin.parseFunctionBody (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:11935:24)
    at JSXParserMixin.parseFunctionBodyAndFinish (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:11921:10)
    at D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:13318:12
    at JSXParserMixin.withSmartMixTopicForbiddingContext (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:12261:14)
    at JSXParserMixin.parseFunction (D:\codebase\pod-webapp\node_modules\@babel\parser\lib\index.js:13317:10) {
  code: 'BABEL_PARSE_ERROR',
  reasonCode: 'AttributeIsEmpty',
  syntaxPlugin: 'jsx',
  loc: Position { line: 149, column: 65, index: 5382 },
  pos: 5382
}

### What's the expected result?

After disabling million in next.config.js
I get this, I guess it should work like that

./src/app/home/orders/detail/page.jsx
 ⚠ Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
 ✓ Compiled /_error in 4.9s (3228 modules)
 ⚠ Fast Refresh had to perform a full reload due to a runtime error.

### Link to Minimal Reproducible Example

cant seem to install next 14.0.4 on stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tobySolutions** [comment] 2024-01-10 19:48
Could you provide screenshots @theaafofficial? I'm going to need a walkthrough of your setup and I'll still need a reproduction though.

Is it that your application totally crashes and doesn't work again?

**Comment by theaafofficial** [comment] 2024-01-10 19:52
sure, what kinda screenshots do you need?
and to your question, no the application doesn't crash, it still runs fine. but whenever I make a change in code, it doesn't reflect in the app due to broken hot-reload ig.

**Comment by tobySolutions** [comment] 2024-01-10 19:55
> sure, what kinda screenshots do you need? and to your question, no the application doesn't crash, it still runs fine. but whenever I make a change in code, it doesn't reflect in the app due to broken hot-reload ig.

The error, your next config and to clarify you are using automatic mode, right?

**Comment by theaafofficial** [comment] 2024-01-10 20:08
Yes, auto.

config file
![image](https://github.com/aidenybai/million/assets/52921754/bb6f3fed-2d14-4995-9a9c-9c96d933e94e)

Flow of error:
- just removed ">"
![image](https://github.com/aidenybai/million/assets/52921754/23f734af-26e5-4af2-b819-044f8a41949d)
- got the error:
![image](https://github.com/aidenybai/million/assets/52921754/e73a40fe-4a87-4e68-ad94-00b7e6cc6428)
- added it ">" back:
![image](https://github.com/aidenybai/million/assets/52921754/97eb7fb8-6d3a-4452-91ed-900bc31785ac)
but the error is still there, it doesn't reload, which isn't a good development experience.

**Comment by tobySolutions** [comment] 2024-01-10 20:10
> Yes, auto.
> 
> config file ![image](https://private-user-images.githubusercontent.com/52921754/295696470-bb6f3fed-2d14-4995-9a9c-9c96d933e94e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MTc2MTMsIm5iZiI6MTcwNDkxNzMxMywicGF0aCI6Ii81MjkyMTc1NC8yOTU2OTY0NzAtYmI2ZjNmZWQtMmQxNC00OTk1LTlhOWMtOWM5NmQ5MzNlOTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDIwMDgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiYzM5ZDFlNDA2NTc1MjIxNTJhMzA4NGNlYzZlMGQzYzhlYmFiNGNhNzc1YjZkYzE5ZmI0MjljMzYzOWQ4NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TUmbrdl6iO1MphpPEPLnOJz7EpPVW7269T6kdtEhaUc)
> 
> Flow of error:
> 
> * just removed ">"
>   ![image](https://private-user-images.githubusercontent.com/52921754/295697339-23f734af-26e5-4af2-b819-044f8a41949d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MTc2MTMsIm5iZiI6MTcwNDkxNzMxMywicGF0aCI6Ii81MjkyMTc1NC8yOTU2OTczMzktMjNmNzM0YWYtMjZlNS00YWYyLWI4MTktMDQ0ZjhhNDE5NDlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDIwMDgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3YjA3N2FlM2NhNjJhYTM3NjVjMjY5OTI1NjI1OGVhNDQ3MTBiMjA1OGFmYjgxYmJkMTYxYzM3NTE2ZjQ3NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CkN86f_oTUMRKu4k5Rz1VgQnBM31ziAQWynz04Ijcio)
> * got the error:
>   ![image](https://private-user-images.githubusercontent.com/52921754/295697542-e73a40fe-4a87-4e68-ad94-00b7e6cc6428.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MTc2MTMsIm5iZiI6MTcwNDkxNzMxMywicGF0aCI6Ii81MjkyMTc1NC8yOTU2OTc1NDItZTczYTQwZmUtNGE4Ny00ZTY4LWFkOTQtMDBiN2U2Y2M2NDI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDIwMDgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwOWI2NjczODVlNTdhNDY5NTI1MzM1NDgxNjNmNjgzZjU4YzlkMjM5MGM5YmRlNjU0M2IzZGI2NWQ4NDM1OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kxzxqvU-iuagdI-SDr-Yuu1L359jYGX_eaiqvMxbRnc)
> * added it ">" back:
>   ![image](https://private-user-images.githubusercontent.com/52921754/295697826-97eb7fb8-6d3a-4452-91ed-900bc31785ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MTc2MTMsIm5iZiI6MTcwNDkxNzMxMywicGF0aCI6Ii81MjkyMTc1NC8yOTU2OTc4MjYtOTdlYjdmYjgtNmQzYS00NDUyLTkxZWQtOTAwYmMzMTc4NWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDIwMDgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjZmI5NDRjMWJmMzQ0ZTY3YzZiNzkyMjRjYjE4NWQ3OTg0MDAyMDUxNGY1ODQ5NDc1NTMwMzQwZjM5MjA0NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ehhtFBRT0vS4ggi_YgURd4jB3x7IUFXc2n927ZA7qoM)
>   but the error is still there, it doesn't reload, which isn't a good development experience.

Thanks for this. I'll discuss this with core team and have conversations with them. Thanks for this, a lot of things like this will be fixed in Million 3.0 though

**Comment by theaafofficial** [comment] 2024-01-10 20:19
Thank you, I noticed one more thing, what compiled initially(like a homepage compiled) works fine after that error but if I click on the page that wasn't compiled before, it gets stuck on compiling
![image](https://github.com/aidenybai/million/assets/52921754/a3022763-15ed-49e1-979f-66dd24d521f3)

**Comment by tobySolutions** [comment] 2024-01-10 20:21
> Thank you, I noticed one more thing, what compiled initially(like a homepage compiled) works fine after that error but if I click on the page that wasn't compiled before, it gets stuck on compiling ![image](https://private-user-images.githubusercontent.com/52921754/295700540-a3022763-15ed-49e1-979f-66dd24d521f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MTgyODYsIm5iZiI6MTcwNDkxNzk4NiwicGF0aCI6Ii81MjkyMTc1NC8yOTU3MDA1NDAtYTMwMjI3NjMtMTVlZC00OWUxLTk3OWYtNjZkZDI0ZDUyMWYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDIwMTk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4MmI5MTUxYWYzOGE4Y2MyZGVlNmVhNzQwN2RjYTgxOTkxMmVkNzI5NmZhMTU1MWVmYzljMjIwOTJjMTVkYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yh2VSa8ll26nN9Bw6LkiuxDCQckf42RgUPqV0Bcul48)

Hmm, that's certainly weird.

**Comment by skushagra9** [comment] 2024-01-16 15:39
please assign me @tobySolutions

**Comment by jahirfiquitiva** [comment] 2024-02-02 22:03
I am facing the same issue with Million.js 2.6.4 ... I haven't been able to use 3.x due to another error: https://github.com/aidenybai/million/issues/936

**Comment by lxsmnsyc** [comment] 2024-02-03 03:13
It's weird. This only happens if you do `example={}` in the JSX. I don't think this is fixable as the error is expected.

**Comment by FlorianLeChat** [comment] 2024-02-06 12:12
I have the same issue with latest version of NextJS 14 and Million but can't find a consistent reproduction path. Sometimes this error disappears for a while after restarting my NextJS local server, but reappears after several hot reloads.

**Comment by Prains** [comment] 2024-02-12 05:32
Have the same issue here.

Appeared for me when i wrote incomplete useState initializer. 

Hot reload became disabled and dev server could not compile other pages until i reloaded fully

**Comment by Prains** [comment] 2024-02-12 06:19
Dig further into the problem:

Error occurs only when incorrect client component file was saved and put to change to the dev server.

Whenever dev server that uses million js compiler finds an error in client component, hot reload dying and compiler stops working with other components, forcing dev to restart the server.

Right now it is a serious DX issue and i have to uninstall compiler so i can develop my project without any further troubles

**Comment by Prains** [comment] 2024-02-12 11:08
> > Dig further into the problem:
> > Error occurs only when incorrect client component file was saved and put to change to the dev server.
> > Whenever dev server that uses million js compiler finds an error in client component, hot reload dying and compiler stops working with other components, forcing dev to restart the server.
> > Right now it is a serious DX issue and i have to uninstall compiler so i can develop my project without any further troubles
> 
> Hmm, thank you for sharing this; you can also help by providing us with steps to reproduce this, but, i will also share this with the team too.

Steps to reproduce:

1. install next js using npx create-next-app@latest
install app with app router, typescript and tailwind, without src folder.

2. create any client component ('use client')

3. create any syntax \ typescript error and save file

4. page should display your error, compiler should display custom million.js typescript error, when navigating through pages console should tell you that some page is compiling, but page should not reload and page compiling will be stuck

**Comment by Aslemammad** [comment] 2024-02-12 12:02
Can we have a stackblitz reproduction?

**Comment by Prains** [comment] 2024-02-12 12:15
> Can we have a stackblitz reproduction?

https://stackblitz.com/edit/stackblitz-starters-rsunbr?file=app%2Fpage.tsx

**Comment by Aslemammad** [comment] 2024-02-20 07:38
@Prains #973 should fix it.

**Comment by Prains** [comment] 2024-02-20 07:39
> @Prains #973 should fix it.

Thank you! Will be happy to check after pull request will get merged

**Comment by Aslemammad** [comment] 2024-02-20 07:42
Sure, I appreciate your help!

**Closed** 2024-02-24 04:58 UTC
Labels: duplicate, 🤖 aspect: dx
