### ISSUE TITLE
bug: Just a wrong h1 tag on the site

### ISSUE THREAD

**Issue by AugustoSavi** [aidenybai/million#248] opened 2022-08-04 11:51 UTC
**Describe the bug**
An unnecessary h1 tag appearing on the site homepage

**To Reproduce**
1. Go to https://millionjs.org/

**Expected behavior**
I believe this h1 tag shouldn't exist

**Screenshots**
![image](https://user-images.githubusercontent.com/32443720/182839744-625aefdf-aff7-4673-a5cf-ee5bc1669419.png)
![image](https://user-images.githubusercontent.com/32443720/182839756-090e5674-5947-47d7-b284-5384685eca40.png)

**Device (please complete the following information):**
 - Browser [chrome]

**Comment by PringlePot** [comment] 2022-08-04 16:38
Oops, this was probably caused by my pull request #246, let me see If I can fix the issue

**Comment by PringlePot** [comment] 2022-08-04 16:47
#249 should fix this issue :)

**Comment by PringlePot** [comment] 2022-08-04 18:34
Should be fixed

**Comment by aidenybai** [comment] 2022-08-04 18:37
great work

**Closed by aidenybai** 2022-08-04 18:37 UTC
Labels: bug
