### ISSUE TITLE
Kitchen Sink: Build A Memory Game

### ISSUE THREAD

**Issue by tobySolutions** [aidenybai/million#609] opened 2023-10-01 21:12 UTC
Build a memory card game where players match pairs of cards that you'll add to the kitchen sink. Feel free to use any existing projects of yours or start one from scratch.

For more information about the Kitchen sink; check out:

- https://sink.million.dev/
- https://github.com/aidenybai/million/blob/main/packages/kitchen-sink/README.md

N.B: **Upon PR review, your usage of Million.js is a plus**

**Comment by sr2005roy** [comment] 2023-10-02 15:40
@tobySolutions can you please assign me this issue
how many levels and cards required? can you please specify

**Comment by tobySolutions** [comment] 2023-10-03 05:21
Hey there @sr2005roy, I think you're at liberty to do anything you like as long as you're using Million. Sure, I can assign you.

**Comment by sr2005roy** [comment] 2023-10-03 13:49
I have added the memory game in Kitchen Sink. Hope you like it :)
reference:
![image](https://github.com/aidenybai/million/assets/122456380/0139df5f-0cdf-4808-bf65-ac5fed2c6f23)
![image](https://github.com/aidenybai/million/assets/122456380/ba811abf-c3cb-4a36-9ef9-2d80752d3947)
![image](https://github.com/aidenybai/million/assets/122456380/4e765879-3a70-4b9a-aba8-3912e4972fe8)

please check and merge the changes :)

**Comment by sr2005roy** [comment] 2023-10-04 22:33
Sorry I had to open a new PR in order to solve that conflict, I hope you find it and merge it successfully to the repo

Kindly check

**Comment by tobySolutions** [comment] 2023-10-04 22:34
> Sorry I had to open a new PR in order to solve that conflict, I hope you find it and merge it successfully to the repo
> 
> Kindly check

Ok, cool. Checking it out now

**Comment by sr2005roy** [comment] 2023-10-06 04:39
@tobySolutions Can you please check my PR

**Comment by sr2005roy** [comment] 2023-10-06 09:18
@tobySolutions Please check the PR and close this issue

**Comment by sr2005roy** [comment] 2023-10-09 14:14
@tobySolutions the previous PR was closed I guess by the bot

Please check this new PR and merge it under hactoberfest-accepted tag :)

**Comment by sr2005roy** [comment] 2023-10-13 16:32
If the job of the issue is completed kindly close it.

**Comment by tobySolutions** [comment] 2023-10-14 06:17
Hey there @sr2005roy, any updates on this? I remember leaving a couple of feedbacks on your PR.

**Comment by sr2005roy** [comment] 2023-10-14 06:46
yes I had created a PR 711
<img width="739" alt="image" src="https://github.com/aidenybai/million/assets/122456380/80e579aa-c3f7-42ca-a4b1-1e9e5c07c2b8">
I don't know why but you had closed it
Can you reopen it and check the updates

**Comment by tobySolutions** [comment] 2023-10-17 22:14
> yes I had created a PR 711 <img alt="image" width="739" src="https://user-images.githubusercontent.com/122456380/275153573-80e579aa-c3f7-42ca-a4b1-1e9e5c07c2b8.png"> I don't know why but you had closed it Can you reopen it and check the updates

Oh, you made updates? I actually closed it cos I didn't really notice any activity there; my bad. Could you maybe make another PR, please? Make sure to pull from main.

**Comment by sr2005roy** [comment] 2023-10-20 10:52
Sorry I was doing that snake game job, I will work on this now and make a new PR by tomorrow after solving the new changes part

**Comment by sr2005roy** [comment] 2023-10-29 17:09
I have created the PR please check @tobySolutions

**Closed** 2023-10-31 11:27 UTC
Labels: good first issue, hacktoberfest
